create
memory table T_USER_REGISTRATION (
    URQ_ID_C VARCHAR(36) NOT NULL,
    URQ_USERNAME_C VARCHAR(50) NOT NULL UNIQUE,
    URQ_EMAIL_C VARCHAR(100),
    URQ_STATUS_C VARCHAR(20) NOT NULL DEFAULT 'pending',
    URQ_CREATEDATE_D DATETIME NOT NULL,
    URQ_DELETEDATE_D DATETIME NOT NULL,
    URQ_DISABLEDATE_D DATETIME NOT NULL,
    PRIMARY KEY (URQ_ID_C) );

update T_CONFIG
set CFG_VALUE_C = '32'
where CFG_ID_C = 'DB_VERSION';